version: '3'

services:
  client_web:
    build: ./web
    restart: unless-stopped
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - API_HOST=server
      - API_PORT=${API_PORT}
    volumes:
      - apk-vol:/data/apk
    depends_on:
      - client_mobile
      - server

  client_mobile:
    build: ./mobile
    volumes:
      - apk-vol:/data/apk

  server:
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    networks:
      - "db-tier"
    build: ./server
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"

  db:
    image: "mongo"
    command: mongod --port ${DB_PORT}
    restart: unless-stopped
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - "db-tier"
    volumes:
      - db-vol:/data/db

networks:
  db-tier:

volumes:
  apk-vol:
  db-vol:
