version: '3'

services:
  client_web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: $REACT_APP_API_URL
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_HOST=server
    env_file:
      - .env
    volumes:
      - apk-vol:/web/build/apk
    ports:
      - "8081:80"
    depends_on:
      - client_mobile
      - server

  client_mobile:
    build: ./mobile
    volumes:
      - apk-vol:/data/apk
    env_file:
      - .env

  server:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    networks:
      - "db-tier"
      - "redis-tier"
    build: ./server
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"

  worker:
    build: ./server
    command: node . worker
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    env_file:
      - .env
    networks:
      - "redis-tier"
      - "db-tier"
    depends_on:
      - redis
      - db

  db:
    image: "mongo:4.0.14"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS
      - MONGO_INITDB_DATABASE=$DB_NAME
    env_file:
      - .env
    ports:
      - '${DB_PORT}:27017'
    networks:
      - "db-tier"
    volumes:
      - db-vol:/data/db
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

  redis:
    image: "redis:buster"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    env_file:
      - .env
    volumes:
      - redis-vol:/data
    networks:
      - "redis-tier"

networks:
  db-tier:
  redis-tier:

volumes:
  apk-vol:
  db-vol:
  redis-vol:
