apiVersion: v1
kind: Service
metadata:
  namespace: __ENVIRONMENT_SLUG__-area
  name: __ENVIRONMENT_SLUG__-area-redis
  labels:
    app: __ENVIRONMENT_SLUG__-area-redis
    ref: __ENVIRONMENT_SLUG__
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: __ENVIRONMENT_SLUG__-area-redis