apiVersion: v1
kind: Service
metadata:
  namespace: __ENVIRONMENT_SLUG__-area
  name: __ENVIRONMENT_SLUG__-area-db
  labels:
    app: __ENVIRONMENT_SLUG__-area-db
    ref: __ENVIRONMENT_SLUG__
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: __ENVIRONMENT_SLUG__-area-db