apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __ENVIRONMENT_SLUG__-area
  name: __ENVIRONMENT_SLUG__-area-worker
  labels:
    app: __ENVIRONMENT_SLUG__-area-worker
    ref: __ENVIRONMENT_SLUG__
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: __ENVIRONMENT_SLUG__-area-worker
      ref: __ENVIRONMENT_SLUG__
  template:
    metadata:
      labels:
        app: __ENVIRONMENT_SLUG__-area-worker
        ref: __ENVIRONMENT_SLUG__
    spec:
      containers:
        - name: area-worker
          image: __REGISTRY_IMAGE__:__REGISTRY_VERSION__
          command: ["node"]
          args: [".", "worker"]
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: __ENVIRONMENT_SLUG__-area-worker
            - secretRef:
                name: __ENVIRONMENT_SLUG__-area-worker